behaviors:
  DriveCar:
    trainer_type: ppo
    hyperparameters:
      batch_size: 768
      buffer_size: 409600
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 0.1
      gail:
        gamma: 0.99
        strength: 1.0
        demo_path: Imitation_Data/Steps10000.demo
    behavioral_cloning:
      strength: 1.0
      demo_path: Imitation_Data/Steps10000.demo
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 10000
